### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by baiej214** [stonerey/RemoteAssistant#3]
16:28:27.1825|ERROR|ChatServer.NLogger|->Server Crash:System.FormatException: GUID 应包含带 4 个短划线的 32
位数(xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)。
   在 System.Guid.TryParseGuidWithNoStyle(String guidString, GuidResult& result)
   在 System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)
   在 System.Guid..ctor(String g)
   在 MySql.Data.Types.MySqlGuid.MySql.Data.Types.IMySqlValue.ReadValue(MySqlPacket packet, Int64 length, Boolean nullVal)
   在 MySql.Data.MySqlClient.NativeDriver.ReadColumnValue(Int32 index, MySqlField field, IMySqlValue valObject)
   在 MySql.Data.MySqlClient.ResultSet.ReadColumnData(Boolean outputParms)
   在 MySql.Data.MySqlClient.ResultSet.NextRow(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlDataReader.Read()
   在 MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   在 MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 MysqlManager.ExecQuery[T](String sql) 位置 D:\Project\CSharpProject\Dll\Server\ChatServer_Source7.3\ChatServer\ChatServer\LogicHandler\MysqlManager.cs:行号 70
   在 ChatServer.LogicHandler.MySqlHandler.Login(UserToken token, DataModel pd) 位置 D:\Project\CSharpProject\Dll\Server\ChatServer_Source7.3\ChatServer\ChatServer\LogicHandler\MySqlHandler.cs:行号 92
   在 ChatServer.LogicHandler.MySqlHandler.OnReceiveData(UserToken token, DataModel pd) 位置 D:\Project\CSharpProject\Dll\Server\ChatServer_Source7.3\ChatServer\ChatServer\LogicHandler\MySqlHandler.cs:行号 42
   在 ChatServer.Handler.HandlerCenter.dgl7DHsJXy2tcmx0gBM(Object , Object , Object )
   在 ChatServer.Handler.HandlerCenter.MessageReceive(UserToken token, Byte[] data) 位置 D:\Project\CSharpProject\Dll\Server\ChatServer_Source7.3\ChatServer\ChatServer\Handler\HandlerCenter.cs:行号 71
   在 NetCore.UserToken.NKZEkklSv2Nho016fx(Object , Object , Object )
   在 NetCore.UserToken.ReadData() 位置 D:\Project\CSharpProject\Dll\Server\ChatServer_Source7.3\ChatServer\ChatServer\NetCore\UserToken.cs:行号 124
   在 NetCore.UserToken.ProcessReceive(SocketAsyncEventArgs e) 位置 D:\Project\CSharpProject\Dll\Server\ChatServer_Source7.3\ChatServer\ChatServer\NetCore\UserToken.cs:行号 83
   在 NetCore.UserToken.ReceiveSAEA_Completed(Object sender, SocketAsyncEventArgs e) 位置 D:\Project\CSharpProject\Dll\Server\ChatServer_Source7.3\ChatServer\ChatServer\NetCore\UserToken.cs:行号 59
   在 System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   在 System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object ignored)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   在 System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   在 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by stonerey** [comment]
数据表中 UserAvatar这一项 设置头像地址
